In [1]:
import os
import pandas as pd

In [2]:
""" Machine Learning Foundational Concepts Review

Three Major sections of ML workflow
1. Data -->(Prepare Data for Training)
   1.1. Data Collection
   1.2. Data Loading
   1.3. Data Cleaning
   1.4. Data Exploration and Visualization
   1.5. Feature Engineering: Feature Selection + Feature Transformation
   1.6. Data Splitting : Train-Test-Validation fairly

2. Model:
    2.1. Machine learning Algorithm
    2.2. Artificial Neural Network
    2.3. AI Algorithm i.e. Genetic Algorithm

3. Training
    Hyperparameters tuning i.e. epochs,learning rate, batch size,regularizer etc.
    Optimizer i.e. Gradient Descent Based. Most popular: Adam Optimizer
    Compute Gradient i.e. Gradient Computation Graph
    Update parameters

Overfitting: Models performance very good on training data but poor on
test data
    Reasons: Model is too big/complex than training data
             Or dataset is too small
    Solution: -Regularization in cost function to give penalty to
               restrict gradient descent to perform too well
              -Ensemble Learning i.e. Prediction is done by more than one algorithms
              -Dropout i.e. Removes some connections from the ANN

Underfitting: Models performance is poor on both training and testing data
    Reasons:Model is too simple to capture the underlying data distributions
    Solution:Select more complex model or algorithm

Generalization(Ideal Case): Models performance is well balanced in both training and testing
""";

# DATA

In [3]:
ROOT_DIR="E:\\BongoDev\\Classification_Analysis"
DATA_DIR=os.path.join(ROOT_DIR,"Data")
DATASET_PATH=os.path.join(DATA_DIR,"housing.csv")

dataset=pd.read_csv(DATASET_PATH)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [5]:
numerical_cols=dataset.select_dtypes(include="number").columns
categorical_col=dataset.select_dtypes(include=['object','str']).columns

print(numerical_cols)
print(categorical_col)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [6]:
# Preprocessing

from sklearn.preprocessing import StandardScaler,LabelEncoder
scaler=StandardScaler()
label_encoder=LabelEncoder()

In [7]:
dataset[numerical_cols]=scaler.fit_transform(dataset[numerical_cols])
dataset[numerical_cols]

        price      area  bedrooms  bathrooms   stories   parking
0    4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1    4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2    4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3    3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4    3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692
..        ...       ...       ...        ...       ...       ...
540 -1.576868 -0.991879 -1.308863  -0.570187 -0.929397  1.517692
541 -1.605149 -1.268613  0.047278  -0.570187 -0.929397 -0.805741
542 -1.614327 -0.705921 -1.308863  -0.570187 -0.929397 -0.805741
543 -1.614327 -1.033389  0.047278  -0.570187 -0.929397 -0.805741
544 -1.614327 -0.599839  0.047278  -0.570187  0.224410 -0.805741

[545 rows x 6 columns]

In [8]:
dataset[categorical_col]=dataset[categorical_col].apply(label_encoder.fit_transform)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0

In [9]:
target_var='prefarea'
dataset[target_var].value_counts()

prefarea
0    417
1    128
Name: count, dtype: int64

In [10]:
X=dataset.drop(columns=target_var)
y=dataset[target_var]

X.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
y_train.value_counts()

prefarea
0    334
1    102
Name: count, dtype: int64

In [13]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (2.4.3)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->imblearn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn

   ---------------------------------------- 0/3 [sklearn-compat]
   ---------------------------------------- 0/3 [sklearn-compat]
   ---------------------------------------- 0/3 [sklearn-compat]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ---------------------------------------- 3/3 [imblearn]

Successfully installed imbalanced-learn-0.14.1 imblearn-0.0 sklearn-compat-0.1.5

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [18]:
from imblearn.over_sampling import SMOTE

smote=SMOTE()
X_train,y_train=smote.fit_resample(X_train,y_train)
y_train.value_counts()

prefarea
0    334
1    334
Name: count, dtype: int64

# MODEL

In [19]:
"""
DECISION TREE
"""
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()

decision_tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
y_pred=decision_tree.predict(X_test)
print(y_pred)

[0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1
 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
 0 0 1 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1]

In [21]:
from sklearn.metrics import accuracy_score,classification_report

accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.6788990825688074

In [ ]:
"""
K-NEAREST NEIGHBOUR

example 1 (e1) = [2, 3]
example 2 (e2)
example 3 (e3)
...
example n  (en)

example (e) = [1, 1]

distance(e1, e) = sqrt((2-1)^2+(3-1)^2) = 0.258
distance(e2, e) = sqrt((2-1)^2+(3-1)^2) = 0.356
distance(e3, e) = sqrt((2-1)^2+(3-1)^2) = 0.197
distance(e4, e) = sqrt((2-1)^2+(3-1)^2) = 0.274

k = 3, Closest to e: e1 (1), e3(1), e4(0) prediction = e (1)
""";

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn_model=KNeighborsClassifier()
knn_model.fit(X_train,y_train)
y_pred=knn_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(accuracy)
print(report)

0.6330275229357798
              precision    recall  f1-score   support

           0       0.82      0.66      0.73        83
           1       0.33      0.54      0.41        26

    accuracy                           0.63       109
   macro avg       0.58      0.60      0.57       109
weighted avg       0.70      0.63      0.66       109