In [1]:
import os
import pandas as pd

In [ ]:
""" Machine Learning Foundational Concepts Review

Three Major sections of ML workflow
1. Data -->(Prepare Data for Training)
   1.1. Data Collection
   1.2. Data Loading
   1.3. Data Cleaning
   1.4. Data Exploration and Visualization
   1.5. Feature Engineering: Feature Selection + Feature Transformation
   1.6. Data Splitting : Train-Test-Validation fairly

2. Model:
    2.1. Machine learning Algorithm
    2.2. Artificial Neural Network
    2.3. AI Algorithm i.e. Genetic Algorithm

3. Training
    Hyperparameters tuning i.e. epochs,learning rate, batch size,regularizer etc.
    Optimizer i.e. Gradient Descent Based. Most popular: Adam Optimizer
    Compute Gradient i.e. Gradient Computation Graph
    Update parameters

Overfitting: Models performance very good on training data but poor on
test data
    Reasons: Model is too big/complex than training data
             Or dataset is too small
    Solution: -Regularization in cost function to give penalty to
               restrict gradient descent to perform too well
              -Ensemble Learning i.e. Prediction is done by more than one algorithms
              -Dropout i.e. Removes some connections from the ANN

Underfitting: Models performance is poor on both training and testing data
    Reasons:Model is too simple to capture the underlying data distributions
    Solution:Select more complex model or algorithm

Generalization(Ideal Case): Models performance is well balanced in both training and testing
""";

# DATA

In [3]:
ROOT_DIR="E:\\BongoDev\\Classification_Analysis"
DATA_DIR=os.path.join(ROOT_DIR,"Data")
DATASET_PATH=os.path.join(DATA_DIR,"housing.csv")

dataset=pd.read_csv(DATASET_PATH)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [10]:
numerical_cols=dataset.select_dtypes(include="number").columns
categorical_col=dataset.select_dtypes(include=['object','str']).columns

print(numerical_cols)
print(categorical_col)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [11]:
# Preprocessing

from sklearn.preprocessing import StandardScaler,LabelEncoder
scaler=StandardScaler()
label_encoder=LabelEncoder()

In [12]:
dataset[numerical_cols]=scaler.fit_transform(dataset[numerical_cols])
dataset[numerical_cols]

        price      area  bedrooms  bathrooms   stories   parking
0    4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1    4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2    4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3    3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4    3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692
..        ...       ...       ...        ...       ...       ...
540 -1.576868 -0.991879 -1.308863  -0.570187 -0.929397  1.517692
541 -1.605149 -1.268613  0.047278  -0.570187 -0.929397 -0.805741
542 -1.614327 -0.705921 -1.308863  -0.570187 -0.929397 -0.805741
543 -1.614327 -1.033389  0.047278  -0.570187 -0.929397 -0.805741
544 -1.614327 -0.599839  0.047278  -0.570187  0.224410 -0.805741

[545 rows x 6 columns]

In [14]:
dataset[categorical_col]=dataset[categorical_col].apply(label_encoder.fit_transform)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0